### ISSUE TITLE
GMT-X and GMT+X timezones mixed

### ISSUE THREAD

**Issue by levonhart** [Epholys/ultz#3]
`tz gmt-3` shows UTC+3 time instead of UTC-3.

**Comment by Epholys** [comment]
Hello!

That's a very weird bug, either there's some subtlety in `pytz` that I don't know, or something is deeply flawed in the project that only GMTs timezones are reversed.

As a workaround, I manually edited the tz-shorthand file to reverse the GMT timezones, it should work now. Please update the extension and confirm that everything works as expected on your side.

**Comment by levonhart** [comment]
Thank you. It works as expected now.

I think it is something to do with `pytz` as you said...
This 9f0749d6ab1fcb99545dae75934b698e5ff975b6 workaround works fine for me.

**Comment by Epholys** [comment]
Awesome, I'm closing the issue now. Thank you for reporting this bug!
